apiVersion: v1
kind: Config
clusters:
- name: "survey"
  cluster:
    server: "https://ec2-44-220-147-135.compute-1.amazonaws.com/k8s/clusters/c-m-54jqmnk6"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN6TXpBdwpPRE13TmpBZUZ3MHlOREV4TXpBeU16RXhORFphRncwek5ERXhNamd5TXpFeE5EWmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56TXpNREE0TXpBMk1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUQySEFodXpnakErdwpoekUyWUV4ZDA1UHN5OUVOYUJkcE94dk40c\
      mdJc1J0dkhEUlYrZmgyVHJKc2s3RkxUUWFOUWxkMjNuNG9KVHc1ClZ1d1c1ak5VbzZOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      GxUMHk2aGlpYis4NE0zWDZHUjk2bmxEbVVpTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUJudQp1M\
      kFOWGM5Y2NrZWE2MkN3M29rMko4Z2hVbm9MUytNcHVwUXdNeVUrQWlFQTM3THZNcU94bU4zTVNTd\
      kw3VWZ4CmthQlFGZXRucGZzRFdkNW5vY1RXaUdVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "survey"
  user:
    token: "kubeconfig-user-5wwz8bp7lq:pmwj46lm9q2lbdqk52x7hxmdfqh28f9rw67v4mx4x25ptwgpdqqt48"


contexts:
- name: "survey"
  context:
    user: "survey"
    cluster: "survey"

current-context: "survey"
