apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMzbGhibUZ0WVRJNlEyaHBibTFoZVdWbFFERXlNdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
