apiVersion: v1
kind: Service
metadata:
  name: survey-service
  labels:
    app: surveyapp
spec:
  selector:
    app: surveyapp
  ports:
    - port: 8080  
      targetPort: 8080  
      protocol: TCP
      name: http
  type: NodePort  
